services:
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: my-app-mongo
  server:
    image: my-app-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment: 
      - PORT=3000
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./backend/:/usr/src/app/
    container_name: my-app-backend
    depends_on:
      - mongo
  app:
    image: my-app-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment: 
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./frontend/:/usr/src/app/
    container_name: my-app-frontend
    ports:
      - 8081:80
    depends_on:
      - server
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy-my-app
    ports:
      - 8080:80
    depends_on:
      - app
      - server
volumes:
  mongo_data:
