services:
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: my-app-mongo-dev
    networks:
      - default
  server:
    image: my-app-backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    environment: 
      - PORT=3000
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./backend/:/usr/src/app/
    container_name: my-app-backend-dev
    depends_on:
      - mongo
    networks:
      - default
  app:
    image: my-app-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    environment: 
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./frontend/:/usr/src/app/
    container_name: my-app-frontend-dev
    depends_on:
      - server
    networks:
      - default
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy-my-app-dev
    ports:
      - 8080:80
    depends_on:
      - app
      - server
    networks:
      - default
volumes:
  mongo_data:

networks:
  default:
    external:
      name: my-net
