services:
  server:
    image: todo-backend-dev
    environment: 
      - PORT=3000
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./todo-backend/:/usr/src/app/
    container_name: todo-backend-dev
    networks:
      - default
  app:
    image: todo-frontend-dev
    environment: 
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./todo-frontend/:/usr/src/app/
    container_name: todo-frontend-dev
    depends_on:
      - server
    networks:
      - default
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
    networks:
      - default

networks:
  default:
    external:
      name: my-net