services:
  server:
    image: todo-backend
    build: .
    environment: 
      - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database rund
      - REDIS_URL=redis://localhost:6379
    ports:
      - 3000:3000
  